#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEFAULT_INSTALL_DIR="$HOME/localcomai"
INSTALL_DIR="${COMAI_INSTALL_DIR:-}"
BIN_DIR="${HOME}/.local/bin"
SYSTEMD_USER_DIR="${HOME}/.config/systemd/user"
SERVICE_NAME="comai-localai.service"
SERVICE_FILE="$SYSTEMD_USER_DIR/$SERVICE_NAME"
REMOVED_ITEMS=()
SKIPPED_ITEMS=()

section() {
  printf '\n== %s ==\n' "$1"
}

removed() {
  REMOVED_ITEMS+=("$1")
  printf 'Removed: %s\n' "$1"
}

skipped() {
  local path="$1"
  local reason="$2"

  SKIPPED_ITEMS+=("$path - $reason")
  printf 'Skipped: %s (%s)\n' "$path" "$reason"
}

expand_path() {
  local value="$1"
  if [[ "$value" == "~" ]]; then
    printf '%s\n' "$HOME"
  elif [[ "${value:0:2}" == "~/" ]]; then
    printf '%s/%s\n' "$HOME" "${value:2}"
  else
    printf '%s\n' "$value"
  fi
}

managed_wrapper_target() {
  local path="$1"
  local target

  [[ -f "$path" ]] || return 1
  grep -q 'Generated by ComAI installer' "$path" 2>/dev/null || return 1

  target="$(sed -n 's/^exec "\([^"]*\)" "\$@"$/\1/p' "$path" | head -n 1)"
  [[ -n "$target" ]] || return 1
  printf '%s\n' "$target"
}

service_install_dir() {
  local start_line target

  [[ -f "$SERVICE_FILE" ]] || return 1
  start_line="$(sed -n 's/^ExecStart=\(.*\)\/scripts\/comai-localai-service\.sh start$/\1/p' "$SERVICE_FILE" | head -n 1)"
  [[ -n "$start_line" ]] || return 1
  target="$(expand_path "$start_line")"
  [[ -x "$target/scripts/comai-localai-service.sh" ]] || return 1
  printf '%s\n' "$target"
}

looks_like_install_dir() {
  local path="$1"
  [[ -x "$path/bin/comai" && -d "$path/lib/comai" && -f "$path/config/comai.yaml" ]]
}

resolve_install_dir() {
  local target

  if [[ -n "$INSTALL_DIR" ]]; then
    expand_path "$INSTALL_DIR"
    return
  fi

  if target="$(managed_wrapper_target "$BIN_DIR/comai")"; then
    printf '%s\n' "${target%/bin/comai}"
    return
  fi

  if target="$(managed_wrapper_target "$BIN_DIR/comi")"; then
    printf '%s\n' "${target%/bin/comai}"
    return
  fi

  if target="$(service_install_dir)"; then
    printf '%s\n' "$target"
    return
  fi

  if [[ ! -d "$ROOT_DIR/.git" ]] && looks_like_install_dir "$ROOT_DIR"; then
    printf '%s\n' "$ROOT_DIR"
    return
  fi

  printf '%s\n' "$DEFAULT_INSTALL_DIR"
}

remove_command_if_owned() {
  local path="$1"
  local expected_target="$2"
  local actual_target

  if [[ -L "$path" ]]; then
    actual_target="$(readlink "$path")"
    if [[ "$actual_target" == "$expected_target" ]]; then
      rm -f "$path"
      removed "$path"
    else
      skipped "$path" "points somewhere else"
    fi
  elif [[ -e "$path" ]]; then
    if grep -q 'Generated by ComAI installer' "$path" 2>/dev/null; then
      rm -f "$path"
      removed "$path"
    else
      skipped "$path" "exists but is not managed by ComAI"
    fi
  fi
}

remove_service_if_owned() {
  if [[ ! -f "$SERVICE_FILE" ]]; then
    return
  fi

  if grep -Fq "ExecStart=$INSTALL_DIR/scripts/comai-localai-service.sh start" "$SERVICE_FILE"; then
    rm -f "$SERVICE_FILE"
    removed "$SERVICE_FILE"
  else
    skipped "$SERVICE_FILE" "not managed by this ComAI install"
  fi
}

remove_install_dir() {
  if [[ ! -d "$INSTALL_DIR" ]]; then
    return
  fi

  if [[ -d "$INSTALL_DIR/.git" ]]; then
    skipped "$INSTALL_DIR" "looks like a source checkout"
    return
  fi

  if ! looks_like_install_dir "$INSTALL_DIR"; then
    skipped "$INSTALL_DIR" "does not look like a ComAI install directory"
    return
  fi

  rm -rf "$INSTALL_DIR"
  removed "$INSTALL_DIR"
}

INSTALL_DIR="$(resolve_install_dir)"

section "ComAI uninstall"
printf 'Resolved install directory: %s\n' "$INSTALL_DIR"

if command -v systemctl >/dev/null 2>&1; then
  printf 'Stopping and disabling user service if it is active: %s\n' "$SERVICE_NAME"
  systemctl --user disable --now "$SERVICE_NAME" >/dev/null 2>&1 || true
else
  printf 'systemctl was not found. Skipping user service stop/disable.\n'
fi

section "Removing files"
remove_service_if_owned

remove_command_if_owned "$BIN_DIR/comai" "$INSTALL_DIR/bin/comai"
remove_command_if_owned "$BIN_DIR/comi" "$INSTALL_DIR/bin/comai"

remove_install_dir

if command -v systemctl >/dev/null 2>&1; then
  systemctl --user daemon-reload >/dev/null 2>&1 || true
fi

section "Result"
if [[ "${#SKIPPED_ITEMS[@]}" -eq 0 && "${#REMOVED_ITEMS[@]}" -gt 0 ]]; then
  printf 'Success: ComAI user files were removed.\n'
elif [[ "${#SKIPPED_ITEMS[@]}" -eq 0 ]]; then
  printf 'Nothing to uninstall: no ComAI user files were found for this install path.\n'
else
  printf 'Finished with skipped items. ComAI files that were safe to remove were removed, but some paths were left untouched.\n'
fi

if [[ "${#REMOVED_ITEMS[@]}" -gt 0 ]]; then
  printf '\nRemoved items:\n'
  printf '  %s\n' "${REMOVED_ITEMS[@]}"
fi

if [[ "${#SKIPPED_ITEMS[@]}" -gt 0 ]]; then
  printf '\nSkipped items:\n'
  printf '  %s\n' "${SKIPPED_ITEMS[@]}"
fi

printf '\nLeft untouched:\n'
if [[ "$ROOT_DIR" != "$INSTALL_DIR" ]]; then
  printf '  %s\n' "$ROOT_DIR"
fi
printf '  %s\n' "$HOME/ai"
