#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_DIR="${COMAI_INSTALL_DIR:-$HOME/localcomai}"
BIN_DIR="${HOME}/.local/bin"
SYSTEMD_USER_DIR="${HOME}/.config/systemd/user"
SERVICE_NAME="comai-localai.service"
SERVICE_FILE="$SYSTEMD_USER_DIR/$SERVICE_NAME"

remove_command_if_owned() {
  local path="$1"
  local expected_target="$2"

  if [[ -L "$path" ]]; then
    if [[ "$(readlink "$path")" == "$expected_target" ]]; then
      rm -f "$path"
      printf 'Removed: %s\n' "$path"
    else
      printf 'Skipped: %s points somewhere else\n' "$path"
    fi
  elif [[ -e "$path" ]]; then
    if grep -q 'Generated by ComAI installer' "$path" 2>/dev/null; then
      rm -f "$path"
      printf 'Removed: %s\n' "$path"
    else
      printf 'Skipped: %s exists but is not managed by ComAI\n' "$path"
    fi
  fi
}

if command -v systemctl >/dev/null 2>&1; then
  systemctl --user disable --now "$SERVICE_NAME" >/dev/null 2>&1 || true
fi

if [[ -f "$SERVICE_FILE" ]]; then
  rm -f "$SERVICE_FILE"
  printf 'Removed: %s\n' "$SERVICE_FILE"
fi

remove_command_if_owned "$BIN_DIR/comai" "$INSTALL_DIR/bin/comai"
remove_command_if_owned "$BIN_DIR/comi" "$INSTALL_DIR/bin/comai"

if [[ -d "$INSTALL_DIR" ]]; then
  rm -rf "$INSTALL_DIR"
  printf 'Removed: %s\n' "$INSTALL_DIR"
fi

if command -v systemctl >/dev/null 2>&1; then
  systemctl --user daemon-reload >/dev/null 2>&1 || true
fi

cat <<EOF
Uninstalled ComAI user files.

Left untouched:
  $ROOT_DIR
  $HOME/ai
EOF
